src/math.ts
src/types.ts

Added color.toArray() since thought i'd be a nice feature<br>
`ex: obj.color.toArray -> [255, 255, 255]`
Re-did the PR on the COOLER kaboom 😎

feat: Color.toArray()

---

src/kaboom.ts

update the version from v3000.1.17 to v3001.0.0 to be more accurate for the end user

change: version stated in constant "VERSION"

---

src/kaboom.ts
src/types.ts

feat: add button choice to onClick

---

.github/ISSUE_TEMPLATE/config.yml

pretty descriptive title, small change

fix: clicking add idea on issues tab now takes you to correct place

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feat.md

updated issue templates, hoping to not have messed anything up! 🙏

chore: updated issue templates

---

src/kaboom.ts

fix: Fixes horizontal velocity when on platform

---

src/kaboom.ts
src/types.ts

Added a function that gets the name of the current scene, tried to avoid adding a property to the game object but i really couldn't find a way to do it, so i just had to add one

feat: added getCurrentScene function

---

examples/linejoin.js
src/components/draw/outline.ts
src/kaboom.ts
src/types.ts

The outline component now has line join and opacity options
Outline opacity overrides fill opacity if set

feat: Adds opacity and line join option to outline

---

README.md

Just checking out the library and noticed the link in the readme has a typo, simple fix

Fix homepage link

---

src/components/transform/pos.ts
src/kaboom.ts
src/types.ts

feat: All transforms needed to change the frame of reference from one place to another

---

examples/draw.js
src/kaboom.ts

This should avoid future problems when identical vertices are added

feat: Protect against invalid input

---

examples/draw.js
src/kaboom.ts
src/math.ts

Level only raycasted obstacle tiles. This adds object support as well.

feat: Raycast objects on tiles

---

CHANGELOG.md
src/components/draw/sprite.ts
src/types.ts

feat: SpriteComp.getCurAnim()

---

CHANGELOG.md
src/components/draw/outline.ts

now when debug inspecting, the outline component will show width of outline and color of outline

feat: inspecting outline displays properties

---

examples/draw.js
examples/linecap.js
src/kaboom.ts

As well as a fix for non looping lines. Last point is now taken under consideration

feat: Square line cap

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feat.md

chore: fixed templates

---

CHANGELOG.md
examples/easing.js
src/kaboom.ts
src/math.ts
src/types.ts

steps creates a staircase function for discontinuous easing
linear uses linear easing with multiple linear segments
cubic-bezier uses bezier easing

feat: added higher order easing functions linear, steps and cubic-bezier

---

README.md

I missed a few since I wasn't sure if it'd be a good idea to change them, although go ahead and edit it if you want

docs: replace some references of kaboom with kaplay

---

.github/PULL_REQUEST_TEMPLATE.md

This PR contains a PR template for new PRs so that maintainers of KAPLAY are able to easily understand the PR.

chore: create PR template for new PRs

---

examples/polygon.js
src/components/draw/polygon.ts
src/kaboom.ts

Fix triangulate option propagation
Better example polygon,
Force triangulation if user requests it

fix: triangulation

---

CHANGELOG.md
examples/binding.js
examples/input.js
src/app.ts
src/kaboom.ts
src/types.ts

It adds support to [Unified Input and Input Bindings](https://github.com/marklovers/kaplay/wiki/Unified-Input-and-Input-Bindings)
fix #142

Unified Input and Input Bindings

---

src/kaboom.ts
src/types.ts

Adds camFlash, takes as a parameter color (WHITE) and a fade out time (1 second), closes https://github.com/marklovers/kaplay/issues/153

feat: camFlash()

---

.github/PULL_REQUEST_TEMPLATE.md

I think the current PR template is kinda annoying, I don't even like to use this, I changed to this, I would like to check if other people likes it

chore: simplify pr template

---

src/assets.ts
src/components/physics/area.ts
src/components/transform/pos.ts
src/components/transform/scale.ts
src/gfx.ts
src/kaboom.ts
src/math.ts
src/types.ts

this pr remove some duplications between gfx, math and types.ts, also moves some cateogires

chore: rm dup types, descriptions, categories

---

CHANGELOG.md
src/app.ts
src/assets.ts
src/components/draw/particles.ts
src/components/draw/sprite.ts
src/components/level/agent.ts
src/components/level/patrol.ts
src/components/level/sentry.ts
src/components/misc/health.ts
src/components/misc/state.ts
src/components/misc/timer.ts
src/components/physics/area.ts
src/components/physics/body.ts
src/components/physics/doubleJump.ts
src/components/transform/offscreen.ts
src/kaboom.ts
src/types.ts
src/utils.ts

Why? Because it interferes with the Event interface from browsers, and it usually bugs with the type generation, and even the autocomplete (something common is you trying to use Event type of kaboom and finish using Event type from browser)
- Closes #145

chore: rename Event to KEvent

---

.github/workflows/test.yml

this will allow for easy real world testing and pen testing for prs and pushes after the fact, this would also allow for end users to be able to have access the latest version of kaplay.
- Related Issue # none
- Closes # none

chore: allow for pkg.pr.new for prs and pushed changes

---

examples/inspectExample.js
src/components/draw/circle.ts
src/components/draw/color.ts
src/components/draw/opacity.ts
src/components/draw/outline.ts
src/components/draw/polygon.ts
src/components/draw/rect.ts
src/components/draw/shader.ts
src/components/draw/sprite.ts
src/components/draw/uvquad.ts
src/components/level/agent.ts
src/components/misc/health.ts
src/components/misc/state.ts
src/components/physics/area.ts
src/components/physics/body.ts
src/components/physics/doubleJump.ts
src/components/transform/anchor.ts
src/components/transform/layer.ts
src/components/transform/pos.ts
src/components/transform/rotate.ts
src/components/transform/scale.ts
src/components/transform/z.ts
src/kaboom.ts

would fix https://github.com/marklovers/kaplay/issues/168, i think i'd be better behaviour
sorry for closing and reopening and closing and reopening im struggling with git right now

feat: support for custom names in inspect 

---

.devcontainer/devcontainer.json
.github/dependabot.yml
.gitignore

Devcontainers for KAPLAY, this allows for anyone to have the same working environment.
- Related Issue #184
- Closes #184

feat: devcontainers

---

src/components/transform/layer.ts

fix: obj.layer not working

---

examples/jsconfig.json

this is the most basic thing i can ever do, just make tests/examples strict
i now gained +10 years of js experience
- Related Issue #N/A
- Closes #N/A

chore: make tests strict

---

.devcontainer/devcontainer.json
src/kaboom.ts

It check all components in `unuse()` searching for dependents. Also I added dprint vscode extension to devcontainer, something necessary.
- Closes #165

fix: unuse allows for removal of needed components

---

src/kaboom.ts
src/types.ts

Allow for `handle` to infer classes, and function component return values.
---

feat: Handle `make` dynamic typing.

---

src/kaboom.ts

Checks the constant VERSION and compares it with local VERSION
- Closes #

fix: better way to detect if an object is KaboomCtx

---

src/kaboom.ts

fix: Pop implicity exists
Type collision

fix: Pop result implicity exists

---

src/components/draw/color.ts

Implement expected overflows for Color
Type collision

fix: Implement expected overflows for Color

---

src/app.ts

fix: Gamepad Typing

---

src/kaboom.ts

fix: use apply for `camFlash`.

---

src/kaboom.ts

Begin typing getTilePath
Type collision

fix: Begin typing `getTilePath`

---

src/kaboom.ts

fix: Handle `raycast` `minHit` cases

---

src/kaboom.ts

`getAt` expects result, so is fine

fix: `getAt` expects result, so is fine

---

src/gfx/shader.ts
src/kaboom.ts

refactor: separate makeShader

---

src/gfx/gfxApp.ts
src/gfx/push.ts
src/kaboom.ts
src/types.ts

refactor: separate pushXXX to gfx/push

---

src/gfx/draw.ts
src/gfx/gfxApp.ts
src/kaboom.ts
src/types.ts

refactor: separate drawRaw

---

CHANGELOG.md
examples/binding.js
src/app/app.ts
src/app/index.ts
src/app/inputBindings.ts
src/game/index.ts
src/kaplay.ts
src/types.ts

`getLastDevice()` returns the state of `lastInputDevice`, and it's setted before fire input events.
- close #147

feat: getLastDevice()

---

src/components/level/agent.ts
src/components/level/patrol.ts
src/components/level/sentry.ts
src/components/misc/animate.ts
src/game/events/eventMap.ts
src/game/events/events.ts
src/game/events/index.ts
src/game/game.ts
src/game/initEvents.ts
src/game/level.ts
src/types.ts
src/utils/events.ts

Types all `on()` events that are in the source related to components and raw game obj

feat: type `on()`

---

examples/easing.js

Easing demo is broken in https://play.kaplayjs.com/?example=easing

Fix easing demo

---

src/app/app.ts
src/app/inputBindings.ts
src/utils/sets.ts

fix: allow the same input button inside different input bindings

---

CHANGELOG.md
src/kaplay.ts

fix: add error when error is not an error

---

CHANGELOG.md

chore: new changelog

---

CHANGELOG.md
CONTRIBUTING.md

chore: v3001 changes

---

CHANGELOG.md
CONTRIBUTING.md
examples/audio.js
examples/text.js
src/assets/asset.ts
src/assets/bitmapFont.ts
src/assets/font.ts
src/assets/sound.ts
src/components/physics/area.ts
src/kaplay.ts

fix: loadFont and loadBitmapFont not working with loadRoot

---

src/app/app.ts

fix: mouseDeltaPos() resetting

---

src/app/app.ts
src/app/index.ts

fix: mouseDeltaPos resetting

---

src/audio/play.ts

Copy of #331  for v3001 branch

Copy changes from #331 for v3001 branch

---

README.md

The README.txt of repo stated that we can create a kaplay project using "create-kaplay mygame" command, but I think it should be "npx create-kaplay mygame"

docs: updated command create-kaplay in README.txt

---

src/components/physics/area.ts

fix: area debug size on scale

---

src/gfx/formatText.ts

Revert "fix: text cropped"

---

src/gfx/formatText.ts

fix: text cropped

---

src/types.ts

doc: add notice to stay() component

---

CHANGELOG.md
src/app/app.ts
src/index.ts
src/types.ts

feat: return gamepad on gamepad events

---

CHANGELOG.md
examples/fakeMouse.js
src/components/misc/fakeMouse.ts
src/components/misc/index.ts
src/components/physics/area.ts
src/index.ts
src/kaplay.ts
src/types.ts

feat: fake mouse

---

examples/fixedUpdate.js
src/game/events/events.ts

feat: Makes onFixedUpdate attach to fixedUpdate

Makes onFixedUpdate attach to fixedUpdate

---

CHANGELOG.md
src/assets/sound.ts

feat: add the ability of loadSound with AudioBuffer

---

src/types.ts

fix: remove lies about setCursor

---

src/app/app.ts

Cherry picking https://github.com/kaplayjs/kaplay/pull/414 onto this branch

fix: buttonDown event triggered twice for gamepads [cherry-pick]

---

src/components/physics/body.ts

Always clear velocity along collision normal

feat: Always clear velocity

---

src/components/physics/body.ts

ref: https://github.com/kaplayjs/kaplay/discussions/424#discussioncomment-10838057

Drag -> Damping

---

CHANGELOG.md
examples/friction.js
examples/restitution.js
src/components/physics/area.ts
src/components/physics/body.ts

feat: Adds restitution and friction

---

CHANGELOG.md
src/game/game.ts
src/game/make.ts
src/game/scenes.ts

fix: stay loose events

---

CHANGELOG.md
src/game/game.ts
src/game/make.ts
src/game/scenes.ts

fix: stay loose events (#434)

---

CHANGELOG.md
src/components/draw/sprite.ts

fixes https://github.com/kaplayjs/kaplay/issues/171

feat: add relativeFrame to spriteComp

---

package.json
pnpm-lock.yaml
scripts/lib.js
src/app/app.ts
tsconfig.dts.json
tsconfig.json

ci: dts generation with tsc, bump dependencies (v3001)

---

src/types.ts

Should've been part of #382, got missed somehow...

Add type to load AudioBuffer in types.ts

---

src/game/level.ts

fix: can't do getTilePathfrom 0,0

---

src/math/math.ts

Cherry picking https://github.com/kaplayjs/kaplay/pull/482 onto this branch

fix: randi now returns 0 or 1 instead of 0 when no args [cherry-pick]

---

src/types.ts

docs: revise isKey/isButton checks and add examples (#484) cherry-pick

---

src/gfx/draw/drawText.ts

docs: describe usage of CharTransform in jsDoc (#486) cherry-pick

---

src/types.ts

chore: update make example

---

examples/fakeMouse.js

fix: what happened

---

examples/textInput.js
src/components/misc/textInput.ts

before, game would crash if user typed "\" or "[" in textInput
now it won't do that

Backslash text input

---

src/gfx/draw/drawDebug.ts

nullness is not cool Javascript

fix: null has no property "toString"

---

examples/onLoadError.js
src/assets/asset.ts
src/game/events/events.ts
src/game/game.ts
src/kaplay.ts
src/types.ts

gives authors the option to bluescreen the whole game if assets fail to load

add onLoadError

---

.github/workflows/test.yml

- Related Issue #525
- Closes #525

fix: no CI errors

---

src/types.ts

hopefully this is more understandable

"better" docs on map and mapc functions

---

src/components/physics/effectors.ts

was passing comp id to .is() which don't work in v4000

Fix effectors

---

CHANGELOG.md

chore: prepare changelog for v3001.0.5

---

.vscode/snippets.code-snippets
CHANGELOG.md
src/types.ts

This add some `@experimental` tags in JSDoc

doc: experimental tags in entries

---

package.json

Added a funding link in package.json, I think that is reflected on NPM

chore: funding in package.json

---

README.md

doc: replace kaboom with kaplay in README.md

---

CHANGELOG.md
src/events/globalEvents.ts

fix: global trigger args not being passed

---

src/components/draw/shader.ts
src/components/physics/area.ts
src/components/transform/follow.ts

Some properties were unnamed and didnt have any clear documentation so this PR has some simple descriptions.

docs: add jsdoc to shader, area and follow properties

---

src/types.ts

adds PosComp and LevelComp to addLevel type definition
- Related Issue #638 
- Closes #638

fix: addLevel type definition

---

src/types.ts

now it tells you that you have to press tags and that tags are loaded as anims

doc: Add clarification to loadAseprite

---

src/app/app.ts

Cherry picking #631 onto this branch

fix: pointer lock undefined catch error for non-promise version [cherry-pick]

---

package.json
pnpm-lock.yaml
tests/auto/kaplay.spec.ts
tests/auto/missingComps.spec.ts
vitest.config.ts

This PR adds a new test system using this cool library I found ![vitest-puppeteer](https://github.com/carbonate-dev/vitest-puppeteer) (go and give an star)
This combines the best of original `scripts/test.js` file and Vitest tests in `tests/auto`.
I think would be also a good idea add eventually a headless mode for improving this.
- Closes #

test: new testing

---

package.json
src/types.ts
tests/auto/color.spec.ts
tests/auto/kaplay.spec.ts
tests/auto/missingComps.spec.ts
tests/auto/plugin.spec.ts
tests/types/plugins.test-d.ts
tests/utils.ts

What title says really
- Closes #

tests: clarify tests in general, add test for plugins

---

src/gfx/draw/drawFormattedText.ts
src/gfx/draw/drawText.ts
src/gfx/formatText.ts
tests/playtests/styleChangeFont.js

closes #620
you can change the font mid-text, and also prevent scale from making the text box wider.

feat: allow changing font mid-text and add stretch in place option

---

src/app/app.ts
src/core/canvas.ts
src/core/engine.ts
src/core/fontCache.ts
src/core/frameRendering.ts
src/ecs/systems/collision.ts
src/game/game.ts
src/game/make.ts
src/gfx/gfx.ts
src/gfx/gfxApp.ts
src/kaplay.ts
tsconfig.json
tsconfig.test.json
vitest.config.ts

Okay I know how this look, let me explain.
I think for add these features #674 and #673, we need a better organized and documented code. Know what depends of what and have the ability of separate all in concerns and features for adding tree shaking in the future. So here's my idea:
- Organize folders
- Document
- Making tests
This basically takes all of the `initXXXX` and moves them to `core/engine.ts` and `createEngine()`. Maybe in the future we can merge all the states in 1. 
Also the collision system is moved to `ecs/systems/collision.ts` also for organization purposes. I think we can use the `ecs` folder for moving `make.ts` and `components` in the future.
Some files and functions (as I commented in the code) should be in other folders, for example we can have a `rendering/` folder …

refactor: Part 1

---

src/math/math.ts

`RNG` was missing jsdocs so I added them

docs: add jsdoc to RNG class

---

examples/shaders/blink.frag
src/gfx/draw/drawFormattedText.ts
src/gfx/draw/drawText.ts
src/gfx/formatText.ts
tests/playtests/textShader.js

...pretty self-explanatory. Enjoy!

feat: allow individual characters to have a shader

---

.github/workflows/format.yml
.vscode/settings.json
CHANGELOG.md
examples/video.js
src/types.ts
tests/playtests/textShader.js

I think I hit everything that still had the `changelog` label on it. as well as the other things that I and others recently added.
let me know if I got anything wrong or misattributed a change

docs: add much to changelog

---

src/audio/play.ts

That's why you never should use ts-ignore
- Closes #

fix: resolveSound is undefined

---

src/gfx/draw/drawDebug.ts

Changed opinion, maaybe unuseful. Also have to refactor drawDebug prob
- Closes #

fix: remove the green dot in mousePos

---

src/types.ts

fix: type correctly onUse and onUnuse

---

.github/ISSUE_TEMPLATE/bug.yml

fix: fix bug.yml

---

CHANGELOG.md

Looks like I overwritten some changes made by dragoncoder

fix: restore changelog

---

examples/curves.js
src/ecs/components/draw/drawon.ts
src/ecs/make.ts
src/types.ts

This address various issues. But mainly reorder, comment and improve some process of make(). I think it should an extensive test (try all examples) before being merged
#706, #701 and #626

refactor: change order of use, make and type make better

---

.vscode/snippets.code-snippets
src/types.ts

chore: remove mentions to v3001.1

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add summary in PR template

---

CHANGELOG.md
src/app/app.ts
src/ecs/components/misc/textInput.ts

closes https://github.com/kaplayjs/kaplay/issues/724

feat: mayus

---

CHANGELOG.md
examples/patrol.js
src/ecs/components/level/patrol.ts
src/types.ts

fix: PatrolComp is not going to last waypoint

---

CHANGELOG.md
src/ecs/make.ts
src/gfx/stack.ts
src/kaplay.ts
src/math/various.ts
src/types.ts

- Layers now work globally, no longer only between siblings.
- Areas no longer struggle with parents whose transform inst't up-to-date.
- Exported step and smoothstep.
- Small circles and arcs use now less points than larger ones.
- Added pushMatrix, storeMatrix and loadIdentity to the stack functions.

Layers, transform update, stack functions, arc points, step and smoothstep

---

examples/lerp.js

fixes https://github.com/kaplayjs/kaplay/issues/752

feat: lerp example

---

examples/lerp.js

examples: fixed some grammar on lerp.js

---

examples/kaboom.js
scripts/lib/build.js
src/app/app.ts
src/core/context.ts
src/core/debug.ts
src/core/engine.ts
src/core/plug.ts
src/core/quit.ts
src/game/initEvents.ts
src/game/savedata.ts
src/game/scenes.ts
src/gfx/canvasBuffer.ts
src/gfx/stack.ts
src/kaplay.ts
tests/tsconfig.json

What title says, also separated many stuff. This is Part 4 I think>?

refactor: separate context creation in core/context PART 4

---

CHANGELOG.md
examples/health.js
src/ecs/components/misc/health.ts

fixes https://github.com/kaplayjs/kaplay/issues/759
Didn't have time to actually make it work, will finish hopefully in a few hours
Makes me wonder, should we remove hurt() and heal() and only run onHeal and onHurt if the original hp is lower or higher when doing an hp setter?

Feat: HealthComp changes

---

help.json
package.json
pnpm-lock.yaml

Added a help menu (pnpm run help) so that you can see descriptions of commands, if my descriptions are incorrect feel free to change them in help.json, if you prefer yaml or toml for the help file I can change that if you want

chore: Help Menu

---

CHANGELOG.md
src/assets/sprite.ts
src/gfx/TexPacker.ts

fix: TexPacker.add wasn't returning in add_single, add_single -> addSingle

---

src/assets/sprite.ts
src/gfx/texPacker.ts

fix: TexPacker.add wasn't returning in add_single, add_single -> addSingle (v3001)

---

package.json
pnpm-lock.yaml
scripts/dev/serve.js
src/ecs/entity/GameObjRaw.ts
tests/playtests/mfbday.js
tests/playtests/paused.js

+feat: now you can use /crew urls in dev mode
Like if you love Git Blame

fix: update wasn't making effect at all and pause events even if created after .paused = true

---

examples/camera.js
examples/clip.js
examples/curves.js
examples/customCompDebug.js
examples/friction.js
examples/ghosthunting.js
examples/layer.js
examples/levelcomp.js
examples/linecap.js
examples/linejoin.js
examples/maze.js
examples/mazeRaycastedLight.js
examples/onLoadError.js
examples/out.js
examples/pauseMenu.js
examples/picture.js
examples/platformEffector.js
examples/restitution.js
tests/playtests/fastLoop.js
tests/playtests/fixedUpdate.js
tests/playtests/parenttest.js
tests/playtests/slice.js

- Updated general data as missing descriptions, title errors or use of tags.
- Also set `camera` and `layer` examples to fixed version until issues resolved.
- And fixed `pauseMenu` example events firing despite paused.

examples: add missing data and fixes

---

CHANGELOG.md
src/app/app.ts

This PR fixes the letterbox/scale support with touch functions.

fix: solve touch positions not being transformed to viewport

---

src/app/app.ts

fix(v3001): solve touch positions not being transformed to viewport

---

src/ecs/entity/GameObjRaw.ts

This is only a change in TypeScript, these variables still exist in GameObjRaw, but now if you want to access it, you need to explicitely type it. Already happened that some users tried to modify _tags directly

feat: Don't expose to user the types for internal GameObjRaw variables

---

src/ecs/components/physics/area.ts

fix: remove unrecheable return code

---

src/app/app.ts
src/core/errors.ts

Yeah, what you most expected, faster errors. KAPLAY needed it, who doesn't love errors? That pretty blue-screen looking at you every time you want to throw away your computer.
[Screencast from 2025-05-26 11-39-21.webm](https://github.com/user-attachments/assets/d1f05fae-f9cd-4f6f-891f-94698cf033e8)
[Screencast from 2025-05-26 11-40-17.webm](https://github.com/user-attachments/assets/db728fb0-1800-41d1-95ff-1865d95e2891)

feat: Faster errors

---

src/ecs/entity/utils.ts
src/ecs/systems/createCollisionSystem.ts
src/gfx/draw/drawDebug.ts
src/math/spatial/sweepandprune.ts

I did not update the hash tree to do the pruning based on paused but seeing that it is unused that should be okay

fix: check paused recursively and on both objects

---

src/ecs/components/draw/blend.ts
src/ecs/components/draw/circle.ts
src/ecs/components/draw/color.ts
src/ecs/components/draw/ellipse.ts
src/ecs/components/draw/mask.ts
src/ecs/components/draw/opacity.ts
src/ecs/components/draw/outline.ts
src/ecs/components/draw/rect.ts
src/ecs/components/draw/shader.ts
src/ecs/components/draw/sprite.ts
src/ecs/components/draw/text.ts
src/ecs/components/misc/health.ts
src/ecs/components/misc/named.ts
src/ecs/components/misc/state.ts
src/ecs/components/misc/stay.ts
src/ecs/components/transform/fixed.ts
src/ecs/components/transform/pos.ts
src/ecs/components/transform/rotate.ts
src/ecs/components/transform/scale.ts
src/ecs/components/transform/z.ts

feat: work on prefabs

---

src/ecs/components/draw/color.ts
src/ecs/components/draw/outline.ts
src/ecs/components/transform/pos.ts
src/ecs/components/transform/scale.ts
src/math/Vec2.ts
src/math/color.ts

used the Color.serialize() and Vec2.serialize() where i could

small prefab work

---

src/core/context.ts
src/game/game.ts
src/game/scenes.ts
src/gfx/gfxApp.ts
src/math/vec3.ts
src/types.ts
tests/playtests/scenepushandpop.js

This changes add methods for pushing and popping scenes from a stack system, is good for page behaviour
```ts
pushScene(id: string, args: ...unknown[])
```
```ts
popScene()
```
check `scenepushandpop.js` test for examples
pls tell me if need changelog or any change

feat: Push and Pop Scenes methods

---

src/ecs/entity/GameObjRaw.ts

is it a fix?
should it be changelogged?
is it fine?

fix: clear inputEvents in GameObj.clearEvents()

---

src/ecs/entity/GameObjRaw.ts
src/gfx/draw/drawCurve.ts

fix: correctly pass RenderProps in drawCurve

---

src/app/app.ts

fix: moving mouse changes input device type

---

CHANGELOG.md
src/core/contextType.ts

Basically I changelog what was missing and I've added a little note for all our changelogers. Also added grouping for a method

feat: Order changelog

---

src/core/contextType.ts

fixes https://github.com/kaplayjs/kaplay/issues/871
should i changelog this?

fix: added overload to type in onButtonPress

---

src/ecs/components/misc/animate.ts
src/math/ai/decisiontree.ts
src/math/ai/rulesystem.ts
src/math/ai/statemachine.ts

fix: eslint errors

---

src/gfx/formatText.ts

fix: compatibility issues in font height calculation with missing TextMetrics props (v3001)
