kaplayjs/kaplay

- src/kaboom.ts
PR originally made by @tejaboy in the original kaboom repository
https://github.com/replit/kaboom/pull/826
Added to this fork because it didn't got merged on the old-kaboom and that person won't probably make it here, so i might as well
> fix: make lifespan require opacity

- .gitignore
- README.md
basically i replaced kaboom with kaplay and changed the links, i also used obsidian so thats why i ignored obsidian files
> chore: rebrand readme to feature new links

- src/kaboom.ts
area apparently used to display "area" when inspecting, now it displays the vector size, in the same format as pos
> fix: area displays size on inspect

- src/kaboom.ts
- src/types.ts
Added a property for kaboomOpt where you can set the key that toggles the debug mode, couldn't find where the defaults in kaboomOpt were defined so i just checked in the line that does the key checking
`app.onKeyPress(!gopt.debugKey ? "f1" : gopt.debugKey, () => debug.inspect = !debug.inspect);`
closes: https://github.com/marklovers/kaplay/issues/46
> feat: added debugKey

- CHANGELOG.md
- src/components/physics/body.ts
- src/kaboom.ts
- src/types.ts
Gravity direction is no longer fixed to down.
Kept backwards compatibility by creating separate methods to get and set direction only.
Old gravity methods return magnitude like before.
> feat: Gravity direction

- src/components/physics/body.ts
- src/kaboom.ts
When gravity is 0, the magnitude should be 0 and direction default (0, 1)
> fix: Fixes 0 gravity

- src/app.ts
The `isFullscreen()` function gets the fullscreen DOM object, but doesn't determine if it's the game canvas or not. When the `letterbox` option is set in the game, going fullscreen on the entire web page will result in the game canvas size changing, but the game resolution not updating, so I've changed the `isFullscreen()` function to work around this issue.
> fix: full screen judgment

- package.json
- pnpm-lock.yaml
- scripts/lib.js
- src/assets.ts
- src/fonts.ts
- src/kaboom.ts
- src/math.ts
- src/types.ts
- src/utils.ts
- tsconfig.json
This PR address to fix issues related to the types duplication between modules, for example `Vec2` between math.ts and types.ts, etc. To do this, an esbuild plugin is used, it generates the declaration files for every module.
The declaration maps adds the possibility of go direct to the source code with clicked in a Symbol, for example `Vec2`
close #126
close #97 
**Note:** Not all replacements to duplicated types are addressed, only `Vec2`, `Asset`, `FontData` and related to events (`Event`, `EventControllers`), they should be addressed, but I don't want much merge conflicts so others will be addressed in others PR. Also the idea is move CompOpts to their own component file 
It also separates `FontData` from `kaboom.ts` to new module `fonts.ts` (may be temp)
> feat: declaration maps, avoid duplicated types

- src/types.ts
> docs: fixed scenename in types.ts

- CHANGELOG.md
- examples/ciTest.json
- examples/textInput.js
- src/components/index.ts
- src/components/misc/textInput.ts
- src/kaboom.ts
- src/types.ts
this allows you to make text input boxes, with this feature you can make any type of ui you want: search boxes, sign up panels, and making a discord client.
- Related Issue #N/A
- Closes #N/A
> feat: text inputs

- src/kaboom.ts
> fix: `drawRaw` vv is a `number[]`

- src/kaboom.ts
fix: (`loadPedit`) if ctx fails, throw, else ensure defined
Ensures types are not undefined.
> fix: (`loadPedit`) if ctx fails, throw, else ensure defined

- src/kaboom.ts
`slice9` arg is null, so must have null type to match class.
> fix: Implicitly set to null, needs to also be null case.

- src/kaboom.ts
- src/types.ts
Ensure `postShader` & `postShaderUniform` is typed
> fix: Ensure `postShader` & `postShaderUniform` is typed

- src/kaboom.ts
Type is of `unknown`, must be casted.
> fix: (`SoundData.fromArrayBuffer`) Type is of `unknown`, must be casted.

- src/kaboom.ts
`slide()`:  Image slice expects `Quad[]`
> fix: Image slice expects `Quad[]`

- src/kaboom.ts
Ensure GL is defined.
When no GL context is passed, WebGL is likely to be unsupported.
> fix: Ensure `gl` is defined.

- src/kaboom.ts
if createSpriteSheet ctx fails, throw, else ensure defined.
> fix: if createSpriteSheet ctx fails, throw, else ensure defined

- src/kaboom.ts
fix: `resolveFont` passes null, add null FN Return type
> fix: `resolveFont` passes null, add null FN Return type

- src/kaboom.ts
If shader error is malformed, throw
Ensure types.
> fix: If shader error is malformed, throw

- src/kaboom.ts
Use `!` for implicitly not falsey on canvas size check.
Causes type issues.
> fix: Checks implicitly ensure values 

- src/components/draw/sprite.ts
ensure loading sprite on load doesn't crash
> Will not throw, we will just have to return before we put any data
cause it'll do it again when the sprite promise finishes
Because what was happening before is that it'll do that, fail, and then crash after the first prop access
> bugfix: ensure loading sprite on load doesn't crash

- src/kaboom.ts
fix: Add more types relating to `onCurCompCleanup` in `make`
Type collision
> fix: Add more types relating to `onCurCompCleanup` in `make`

- src/kaboom.ts
> fix: `getCost` expects `costMap`

- src/kaboom.ts
getSpatialMap expects result to be made after check 
Type collision
> fix: `getSpatialMap` expects result to be made after check

- src/kaboom.ts
fix: `createConnectivityMap` can be silenced with non-null
> fix: `createConnectivityMap` can be silenced with non-null

- examples/multiboom.js
- src/components/draw/rect.ts
- src/core/context.ts
- src/gfx/draw.ts
- src/gfx/gfxApp.ts
- src/gfx/index.ts
- src/gfx/push.ts
- src/kaboom.ts
In one of my previous PR I broke compatibility between various kaplay instances, so I added a new way to handle context.
In kaplay() function, there's some core parts of our game
```js
const app = initApp();
const gfx = initGfx();
```
And some functions (that before was inside kaplay()) used this context
```js
function pushTransform() {
gfx.transformStack.push(gfx.transform.clone());
}
```
This function `depends` of gfx variable, and then is exported to the kaplay context.
But when we advance with modulization, gfx is still inside `kaplay()`, but now pushTransform is in another file. A previous solution was use `getKaboomContext`.
```js
export function pushTransform() {
const { _k } = getKaboomContext(this);
const { gfx } = _k;
gfx.transformStack.push(gfx.transform.clone());
}
```
Being …
> fix: new ctx, multiboom

- examples/text.js
- src/constants.ts
- src/gfx/formatText.ts
Previously, stacking multiple styles (e.g., `[wavy][rainbow]styled[/rainbow][/wavy]`) would result in text being styled with only the outer-most style tag (in this case, `[wavy]`). This PR changes the inner logic of `compileStyledText` to correctly apply all nested styles.
- Closes #124
> feat: support stacking text styles

- CONTRIBUTING.md
- examples/add.js
it should be called `kaplay` instead of `kaboom` now, right ?
> chore: fix typo in add example

- src/components/physics/body.ts
- src/kaplay.ts
Put physics back on update until we have a benchmark for it to know whether it is identical
> fix: put physics back on update until it is sped up

- CHANGELOG.md
- src/math/math.ts
added small utils to vec2 relalted to arrays
> feat: array utils for vec2

- src/types.ts
Change non-existing component `solid()` to its homologous `body({ isStatic: true })` inside the addLevel example.
> docs: change non-existing component in addLevel example

- src/components/draw/sprite.ts
Fixes typo in deprecation comment.
`getCurrentAnim().name` -> `getCurAnim().name` as `getCurrentAnim()` does not exist.
> chore: fix typo in current anim name hint

- CHANGELOG.md
- src/components/draw/sprite.ts
From Changelog:
- `sprite()` new methods, `getAnim`, `hasAnim`
```js
const obj = add([
sprite("bean"),
]);
// check if an animation exists
debug.log(obj.hasAnim("walk"));
// get the animation data
debug.log(obj.getAnim("walk"));
```
- Close #265
> feat: get sprite anims

- examples/audio.js
- examples/text.js
- src/assets/asset.ts
- src/assets/bitmapFont.ts
- src/assets/font.ts
- src/assets/sound.ts
> fix: loadFont and loadBitmapFont not working with loadRoot

- src/audio/play.ts
> feat: add panner node into play() pipeline

- CHANGELOG.md
- src/app/app.ts
- src/app/inputBindings.ts
New syntax:
```js
kaplay({
buttons: {
"jump": {
"keyboardCode": ["Period", "Space"],
}
}
})
```
- Closes #368
> feat: add keyboardCode on input bindings

- examples/gravity.js
In examples/gravity, the given link is "https://kaboomjs.com#BodyComp", I replaced it with "https://kaplayjs.com/doc/BodyComp"
> docs(examples): link for BodyComp api

- src/audio/play.ts
- src/audio/playMusic.ts
allows the user to redirect the audio from play() to a different audio node other than Kaplay's global gain node
> feat: connect play() audio to somewhere other than default node

- src/components/physics/area.ts
- src/kaplay.ts
ref: https://github.com/kaplayjs/kaplay/issues/381#issuecomment-2324826289
@mflerackers : "translate and scale transforms were done in the wrong order before drawing for some reason. It's an easy fix..."
is this the fix?
closes #381 if it is
> swap translate <--> scale transforms

- src/audio/play.ts
#331 / #335 implemented the panning but I just noticed that if the audio is paused/stopped/seeked the audio will stop going through the pan node, this PR fixes that.
> fix: unexpected re-route when audio playback is manipulated

- src/app/app.ts
Event `buttonDown` is triggered twice for gamepads. Fix just allows gamepad to be processed separately as intended, if the currently held down button has bindings for it.
- `buttonDown` event triggered twice for gamepad button in use with `onButtonDown()`
- `buttonDown` event triggered three times when holding the same bound buttons at once, e.g. `"dpad-right"` and keyboard `"right"` as defined buttons for input binding `"right"`.
Player could run at twice the speed when using just gamepad, or even three times fast when using both keyboard and gamepad at the same time. And was called Forrest as a result. 🏃‍♂️
[KAPLAYGROUND example link](https://play.kaplayjs.com/?code=eJx9VE1r20AQvetXDCKEVSPbspum4NQ9lEJ7yCGQQg%2FG4LU0loXlXbG7cghB%2F72zu7IluSa6SJp58%2BbNx%2B6eVyV%2FY%2B8B0LPh6T5XshbZHJafpzF …
> fix: buttonDown event triggered twice for gamepads

- src/math/math.ts
> closest orthagonal distance function

- src/components/physics/body.ts
turn restitution to 0.5 in the `restitution` example, the bean will eventually stop moving, but friction is 0 so that is wrong
this fixes that
> fix: restitution was acting like friction when 0 < restitution < friction

- src/game/make.ts
- src/utils/events.ts
My previous PR doing this was a problem. The KEventController wasn't updated. This one adds it.
> fix: stay events reference is not updated on event swich

- src/types.ts
Fixed spelling mistakes in types.ts, it seems that some parts of the code have been formatted differently after running `dprint fmt`
> docs: fix spelling mistakes in jsdoc (+ a bit of formatting)

- src/types.ts
Formatting with `dprint fmt` also formatted other jsdoc comments that I didnt want to edit, not sure why ¯\_(ツ)_/¯
> docs: Add examples for opacity(), z(), follow(), onHoverUpdate() and onScroll()

- src/types.ts
this was noticed before but nobody did a pr
I know it works cause I did it, with a `// @ts-ignore`
> add circle opt to types.ts

- src/app/app.ts
- src/game/events/events.ts
- src/types.ts
> fix: some functions not return a KEventController

- src/components/physics/effectors.ts
The shouldCollide function of the platform effector is now called with the game object as the "this" argument, so it can refer to its own properties.
> fix: platformEffector shouldCollide this argument

- examples/audio.js
- examples/weirdTextTags.js
- src/constants.ts
- src/gfx/formatText.ts
now throws errors if the tags aren't proper or otherwise escaped
closes #448
> fix: rewrite compileStyledText parser

- examples/prettyDebug.js
- src/gfx/draw/drawDebug.ts
- src/kaplay.ts
the new parser I added in #472 is so strict that if you do `debug.log("[boom]")` it crashes the game.
this fixes that, and also causes it to display a dump of the object when you log an object by itself instead of just doing `[object Object]`.
> fix: brackets causing issues in debug.log + enhance logging of single object

- src/math/math.ts
It burned me as in docs it says:
> [randi](https://kaplayjs.com/doc/ctx/randi/#randi)(): number
> rand() but floored to integer.
> 
> `randi() // returns either 0 or 1`
So this will be true after the fix. Because now it always returns 0.
I labeled this as a fix, cause even if it's marked as a Todo in the code, docs made you believe it should work which resulted in bugs.
> fix: randi now returns 0 or 1 instead of 0 when no args

- src/types.ts
The most notable edition is making `isButton..()` methods obvious that param is optional, that check for any button is also possible, not only for certain. I've just stumbled across this in the docs and thought it's not possible.
As I was adding that, I went through all `isButton..()` and `isKey..()` check methods and added some basic examples as well, so there's use of all options like e.g.:
```js
isKeyDown()
isKeyDown("jump")
isKeyDown(["left", "right"])
```
It covers the following:
```js
isKeyDown()
isKeyPressed()
isKeyPressedRepeat()
isKeyReleased()
isButtonPressed()
isButtonDown()
isButtonReleased()
```
> docs: revise isKey/isButton checks and add examples

- examples/physicsfactory.js
- src/components/physics/effectors.ts
also added globalAngle to constantForce
> fix: change area effector to rectangular coordinates

- src/gfx/draw/drawText.ts
Attempts to describe usage of CharTransform. Critique welcome!
> docs: describe usage of CharTransform in jsDoc

- src/components/draw/particles.ts
- src/components/level/pathfinder.ts
- src/components/level/patrol.ts
- src/components/level/sentry.ts
When browsing the code I discovered that some attempted doc comments used the incorrect JSDoc prefix (`/*` instead of `/**`). This results in those comments not being picked up by JSDoc, and thus not in the documentation or in-editor hints.
> docs: fix usage of incorrect JSDoc prefix

- examples/prettyDebug.js
- src/gfx/draw/drawDebug.ts
would previously throw a RecursionError if you try to debug.log a recursive / self-referential object, now it doesn't and just shows `<recursive>` instead
> fix: don't blow stack on recursive object

- examples/fastLoop.js
- src/components/misc/timer.ts
- src/types.ts
mostly from https://github.com/kaplayjs/kaplay/issues/35#issuecomment-2126209484 but can run multiple loops per frame, more up to date stuff etc
mostly if the old loop() was had too low an interval, or the game lagged, then the loop() would deadlock on something and freeze the whole browser window, it doesn't seem to do that anymore even when running 10,000 loops per second (>>framerate)
> fix: fast loop using update

- src/game/make.ts
previously, it would just say "duplicate property width" and you'd be left wondering which components conflict
> feat: add better error message to say which components conflict

- src/kaplay.ts
- src/types.ts
add getter to Canvas for low level frame buffer
> fix: `get fb`

- CHANGELOG.md
- examples/camera.js
- examples/concert.js
- examples/largeTexture.js
- examples/platformBox.js
- examples/platformEffector.js
- examples/platformer.js
- examples/spriteatlas.js
- src/audio/volume.ts
- src/game/camera.ts
- src/game/layers.ts
- src/kaplay.ts
- src/types.ts
- Added `getLayers()` to get the layers list
- Added `getDefaulLayer()` to get the default layer
- Deprecated camera methods `camScale()`, `camPos()` and `camRot()` in favor of
`setCamScale()`, `getCamScale()`, `setCamPos()`, `getCamPos()`, `setCamRot()`
and `getCamRot`.
- Deprecated `camFlash()` in favor of `flash()`, for a `shake()`-like name.
- Deprecated `camTransform()` in favor of `getCamTransform()`.
> feat: normalize get/set methods for camera, add getLayers and getDefaultLayer

- src/audio/playMusic.ts
Sets `loop` using the passed in AudioPlayOpt, similar to how `play()` does.
Closes #527
> fix: sets loop using passed in AudioPlayOpt when playing music

- src/types.ts
Documentation for loadShaderURL was using text from loadShader. Found this while loading a shader during KAJAM
> docs: Added correct function call for loadShaderURL

- examples/sokoban.js
- src/components/level/tile.ts
- src/game/level.ts
- src/types.ts
- Expose removeFromSpatialMap and insertIntoSpatialMap from level so they can be called from the tile component.
- When calling a move function from tile, remove the current component from the spatial map and add them back with the new position.
- Contribute a Sokoban example that showcases using tile movement to create a tile-based puzzle game.
Here's what the example looks like:
- Closes https://github.com/kaplayjs/kaplay/issues/503
> fix: Update level spatial map when tiles are moved

- CHANGELOG.md
- src/gfx/formatText.ts
- src/gfx/gfx.ts
- src/gfx/gfxApp.ts
This fixes strange artifacts appearing with some fonts loaded with `loadFont`
> fix: text artifacts in TrueType fonts

- src/constants.ts
- src/kaplay.ts
- src/types.ts
- src/utils/events.ts
Adds support for `k.cancel()`, a new way to cancel events in KAPLAY. As discussed on Discord, `k.cancel` is a method (when it could just be a property) to signify that it has an "action", to maybe help beginners better understand it.
```js
k.onKeyPress((key) => {
if (key === "q") return k.cancel();
});
```
> feat: add k.cancel()

- src/types.ts
> chore:  incorrect await example is removed from tween docs

- src/math/math.ts
https://open.spotify.com/track/6r9qiF8mkpNsIOwS1lL1J1?si=70eaf570ae8b411d
> docs: added some missing docs for vectors

- CHANGELOG.md
two typos
one was actually quite old
> fix: typos in changelog

- src/components/misc/textInput.ts
textInput claimed it was the stay component
> doc: wrong reference

- src/components/draw/text.ts
- src/gfx/draw/drawText.ts
- src/gfx/formatText.ts
- tests/playtests/textwrap.js
> feat: text wrap all lines using flag

- src/game/make.ts
remove() / destroy() set parent to null. the parent setter would then try to add `this` to the children of null and crash. now it doesn't.
> fix: parent set to null

- CHANGELOG.md
- src/components/draw/text.ts
- src/game/make.ts
- src/gfx/draw/drawText.ts
- src/gfx/formatText.ts
- tests/playtests/styleOverride.js
- tests/playtests/textwrap.js
This changes applies for both versions, v3001 and v4000 and makes strict() only acceept type object or string, otherwise will throw an error. I hope it will help with cases like passing smt is returning undefined, or an extra comma.
> feat: strict .use()

- src/game/make.ts
In #562, a setter method for the `parent` property was introduced. This setter uses a `.splice` call to modify the children of the game object. However, in the `remove` game object method, we first set the parent to null, which triggers 1 splice call. Immediately after setting the parent to null, we perform another splice call. This is problematic because it results in 2 game objects being removed instead of 1.
Steps to reproduce:
- Use the current `master` branch
- Create a game with at least 2 game objects.
- Delete the game object that was created first
Example:
```js
const a = add([
text("test 1", {
size: 50
}),
color("#ff0000"),
pos(width() / 2, height() / 2),
fixed()
])
const b = add([
text("test 2", {
size: 50
}),
color("#ff0000"),
pos(width() / 2, height() / 2 + 50),
fixed()
]) …
```
> fix: fix unintentional children mutation

- CHANGELOG.md
- examples/lifespan.js
- examples/particle.js
- package.json
- src/components/misc/lifespan.ts
- src/types.ts
> fix: lifespan using async

- examples/frames.js
- src/assets/sprite.ts
- src/components/draw/sprite.ts
- src/types.ts
> feat: add frames list option to sprite animation

- src/components/physics/area.ts
- src/components/transform/pos.ts
> fix: screenPos() worldPos() correctly type set functionality (and other type errors)

- src/components/physics/effectors.ts
Several people on the discord have been confused by exactly what the vectors in ignoreSides mean... hopefully this will clear up that confusion.
> doc: clarify meaning of ignoreSides in platformEffector

- src/kaplay.ts
- src/types.ts
adds a global option to change the SAP direction.
> expose option for sweepandprune both directions so it can be tested in external games

- examples/curves.js
- src/events/globalEvents.ts
- src/game/game.ts
- src/game/make.ts
- src/game/scenes.ts
Hopefully this should make the evnt system a little faster, the tag-based events in particular.
Previously tag-baed events fired on all objects, but just returned early if the object wasn't the right tag; now, using the onTag and onUntag events the handlers are dynamically added and removed when tags change, reducing the overhead on each handler.
The big 3 per-frame events (onUpdate, onfixedUpdate, and onDraw) and also now handled using inlined `KEvent`s so that the routing overhead and extra function calls of looking up the named event handler in `KEventHandler` goes away.
> perf: make events somewhat faster

- src/math/math.ts
- src/math/vec3.ts
The static `dot` method on `Vec2` and the regular `dot` on `Vec3` were calculated wrongly. This PR resolved these miscalculations.
> fix: wrong calculation in vector dot

- src/gfx/draw/drawDebug.ts
They now show as `tag: happy` instead of just `happy`, but I think that's more clear that it's a tag and not a component, now that tags are not emulated with anonymous components.
I think it's relatively unlikely that someone is going to create a custom component and give it the id "tag" and also have it make an identical inspect() value to what tags show as here.
> fix: inspect view now shows the tags even after the tagsAsComponents refactor

- src/app/app.ts
Fixes console undefined error when using [setCursorLocked()](https://kaplayjs.com/doc/ctx/setCursorLocked/#setCursorLocked). Problem is when the browser uses non-promise version of `requestPointerLock`. Code doesn't check for optional `catch` property properly.
> fix: pointer lock undefined catch error for non-promise version

- src/components/physics/body.ts
- src/game/make.ts
- src/kaplay.ts
- src/types.ts
- tests/playtests/missing_comps.js
- tests/playtests/missing_comps_dynamic.js
Looks like before and from Kaboom.js, errors in object creation weren't taked in account, so I've added a try catch block for it. The second thing it's that the event that checks dependencies was being running after the comp.add who depends of a dependency, so the first error appearing always was smt like `this.pos it's undefined` (for require: ["pos"] cases)
So the effects of this PR are:
- Add error screen for obj creation errores
- Add the `checkDeps` event before `comp.add`
- Move `handleErr` (the bluescreen func) to `_k`
- Now `handleErr`, error screen and onError it's executed once (as an old TODO wanted)
I added handleErr directly on `checkDeps`, because you can also run checkDeps using `.use` and that not being handled by any event
- Closes #637
> fix: catch errors for missing dependencies in object creation

- src/gfx/draw/drawDebug.ts
- src/types.ts
I have a whole bunch of levels that are swapped in and out by pausing and unpausing them, but the debug inspect doesn't look at whether the object is paused, and the areas from the first level basically "cover" the active level and prevent me from inspecting it.
This changes it so it only inspects the unpaused objects.
@lajbel should this be changeable by a global option?
> fix: only select an object for inspecting if the object is not paused

- README.md
The `README.md` file misspells "thanks" as "thansk"
> chore: correct misspelling in README.md

- src/components/misc/timer.ts
- tests/playtests/wait1.js
when using wait(), the callback was called after N seconds as it should but the onEnd()/then() callbacks were called after 2N seconds because of a stupid off-by-one error. this fixes that.
> fix: timer was waiting 2 loops to call onEnd instead of immediately on the last loop

- src/components/transform/offscreen.ts
if the object size is changed to be greater than the initially specified offscreen distance, then this allows the offscreen distance to be changed so it won't actually disappear until it goes offscreen. additionally the object will use whether its bounding rectangle is truly offscreen if the distance is not specified.
> fix: make offscreen component able to change the offscreen distance

- CHANGELOG.md
- src/game/make.ts
- src/types.ts
- tests/types/GameObj.test-d.ts
This makes `add()` and `make()` convert their arrays to tuples so types like { a: string, b: string } | { a: string } are not converted to { a: string } but mantained as an Union. Also it add comments to some of the weirdest KAPLAY TypeScript methods.
I know I added much `as` in the make code but I don't think really worth making it correctly, only will slow types. This is only for user end
- Closes #645
> feat: tuple component list

- CHANGELOG.md
- src/game/make.ts
- src/kaplay.ts
- src/types.ts
- tests/playtests/largeTexture.js
- tests/types/GameObj.test-d.ts
This removes `make()`, a function that no one liked (except me).
This isn't the end, but a farewell. I love you, make; thanks for giving so much, sorry for not giving anything.
- Closes #664
> feat: Send `make()` to the doom

- src/game/make.ts
- tests/types/add.test-d.ts
It explains some things in the make code (for the next KAPLAY Team generations)
It also renames GameObj type test to add, because it's focused to add, I have to add tests
for GameObj type in general (methods, etc)
- Closes #
> chore: clarify make code and rename GameObj test to add

- src/core/debug.ts
- src/core/engine.ts
- src/core/errors.ts
- src/core/frameRendering.ts
- src/ecs/make.ts
- src/events/eventMap.ts
- src/game/game.ts
- src/game/index.ts
- src/game/initEvents.ts
- src/game/kaboom.ts
- src/game/systems.ts
- src/gfx/draw/drawText.ts
- src/gfx/formatText.ts
- src/gfx/gfxApp.ts
- src/gfx/viewport.ts
- src/kaplay.ts
- src/types.ts
- tests/playtests/styleChangeFont.js
> "yup, that's me, you're probably wondering how i ended up in this situation"
Will summarize changes
- Moved `make.ts` to `ecs/make.ts`
- Moved debug stuff to `src/core/debug.ts` and now it's part of `createEngine`
- Moved `frameUpdate` and `fixedFrameUpdate` to `frameRendering` (ik is not rendering, but well, names are a draft, maybe it can be frameProcessor or frameRunner)
- Moved `handleErr` to `src/core/error.ts`
- Strictly typed `game.events` and `initGame` return type (`Game` type is now explicit, not inferred)
- Removed `KAPLAYInternal` type replaced by `Engine`
Then most changes are variable updates, I tried to mantain names that's why I backed `gfx` to `ggl` and `appGfx` to `gfx`. The idea is change it later. This PR makes code more cleaner, organization better. As I said …
> refactor: Part 2

- src/ecs/components/draw/text.ts
- src/gfx/draw/drawFormattedText.ts
- src/gfx/draw/drawText.ts
- src/gfx/formatText.ts
- src/kaplay.ts
- src/types.ts
- tests/playtests/bigText.js
- tests/playtests/pausedText.js
- tests/playtests/textUnparse.js
closes #509
closes #672
* compileStyledText is exposed, as well as a getter method formattedText() on the text component
* since the formattedText() object contains a renderedText property, the renderedText getter on the text comp is removed.
* fixes some state issues in the text component (text comp will stop recalculating the formatting if it is paused but not hidden -- this was intended but not implemented per a comment that I deleted)
* when I added the stretchy text characters in #676, I only made them stretch by x direction, now if stretchInPlace is false they will also stretch in the y-direction, and the line will get taller as a result.
* also, the doc comment listed the default for stretchInPlace to be false, but it was actually true.
> feat: Text formatting API exposed and fix line height of stretching characters

- src/math/math.ts
- src/types.ts
closes #685
I made the function go from -1 to 1 as it was for backwards compatibility, but yeah the function going from 0 to 1 instead makes more sense, like the glsl mix() function.
> fix: make wave() able to lerp any lerpable value

- examples/fastLoop.js
- examples/raycastObject.js
- examples/raycastShape.js
* the loop example explicitly passed in a loop count of -1, which is not supported anymore to mean "infinity".
* the raycast examples still used unuse when they meant untag, which resulted in the onMouseRelease handler not releasing the selected objects and they got stuck to the mouse.
> fix: some examples were bugged

- CHANGELOG.md
- src/ecs/components/misc/textInput.ts
closes #716
* adds four events to detect when the input is focused, loses focus, receives input, and is updated with changes
* makes the focus property a one hot lockout among all text inputs
> feat: improve text input

- src/ecs/components/draw/video.ts
Added getRenderProps on the video component draw function
closes #717
> fix: use getRenderProps for video draw

- src/components/physics/area.ts
> fix: use an object event instead of an app event in AreaComp.onClick

- src/app/appEvents.ts
- src/core/engine.ts
- src/gfx/canvas.ts
- src/gfx/gfxApp.ts
- src/types.ts
I made this with the idea of in the future maybe have an API for change internal scale (actually, user could modifying _k.globalOpt), so all places that was before referring to the globalScale, now are gopt.scale, also introduces the type MustKAPLAYOpt that is basically where we define the default options (actually, only scale to 1), you can see it in engine.ts
> feat: use only one source of scale

- CHANGELOG.md
- src/assets/bitmapFont.ts
- src/assets/font.ts
Basically, what title says. Little PR :p
> doc: Add default doc in BitmapFont Opt, remove unused outline option and remove another BinaryData type

- src/types.ts
default is false but I put true for some unknown reason
> doc: typo in sprite play opt

- src/components/misc/textInput.ts
Objects with textInput with non-focused get cleared when hitting backspace. Only those with focus should be cleared.
> fix: textInput Component backspace v3001

- CHANGELOG.md
- src/assets/asset.ts
- src/assets/bitmapFont.ts
- src/core/context.ts
- src/gfx/formatText.ts
- src/types.ts
- tests/playtests/spriteAsFont.js
also fixed a bug in the formatText that prevented some bitmap fonts from getting the right texture assigned or having the texture obliterated or needlessly creating an atlas and texture which will not be used
closes #804
> feat: allow sprites to be used as a font

- CHANGELOG.md
- src/ecs/entity/GameObjRaw.ts
The error was happening because we haven't removed the functionality of `children.forEach...`. It was used for registering "add" events of obj's' children added using `make()`
close #805
> fix: tiles in level have their add hooks run twice

- CHANGELOG.md
- src/core/errors.ts
- tests/playtests/errorWithBrackets.js
> I often get Uncaught Error: Styled text error: unclosed tags corner instead of the actual error
> fix: brackets in error msg no longer cause an error when drawing error screen

- src/.env.d.ts
- src/assets/utils.ts
- src/core/engine.ts
This feature is interesting for building tools (like KAPLAYGROUND) setting aliases to paths in assets url, with this feature we could do:
```js
window.kaplayjs_assetsAliases["beansrc"] = "Base64URLHere";
loadSprite("bean", "beansrc"); // now beansrc will be replaced with the alias
```
> feat: assets aliases

- src/ecs/entity/make.ts
- src/game/game.ts
`add()` wasn't possible, now it is, just a little check if arr is undefined, so it skips the .use()/.tag() operations
> fix: support add without compList

- src/assets/shader.ts
This literally changes nothing. Functionally at least, but now it moves the actual compilation of the GLSL into a separate method, that is just called by the constructor.
That way, I can write a plugin to monkeypatch the new compile() method to be able to do stuff like `#include` stuff and still be able to load shaders via `loadShader()` because the Shader compilation has been patched like so
```js
const Shader = _k.gfx.defShader.constructor;
const oldCompile = Shader.prototype.compile;
Shader.prototype.compile = function(vert, frag, attribs) {
/* do some string processing here */
return oldCompile.call(this, vert, frag, attribs);
}
```
> feat: enable shader to be monkeypatched

- src/ecs/components/physics/area.ts
now that #849 was merged I have started to notice that the area object can ocasionally trigger the 'area() requires the obj to have an id' error when it collides with a destroyed object in the tick immediately after it is destroyed but before it is removed from the physics system. This makes the area component ignore objects that don't exist() which is probably what was intended anyway.
(For example, launch the platformer example, and then stomp on a ghosty.)
> fix: ignore destroyed objects when colliding

- CHANGELOG.md
- src/data/gamepad.json
- src/types.ts
includes new button 'touchpad'
i discovered this by accident lol. opened the 'gamepad' example in chrome and pressed the touchpad, and it logged 'undefined'.
> feat: add gamepad definition for ps5 controller

- CHANGELOG.md
- src/assets/shader.ts
This also checks the final program error log and reports any errors there, in case the program was syntactically correct and compiles, but still can't be linked into a runnable shader.
I have not been able to trigger this bug in the kaplayground for some reason... but it nonetheless occurred in my game so I'm fixing it
> fix: also check gl.getProgramInfoLog for errors

- CHANGELOG.md
- src/assets/asset.ts
- src/core/engine.ts
- src/gfx/draw/drawUVQuad.ts
- src/gfx/gfxApp.ts
- src/types.ts
- tests/playtests/pixelPerfect.js
It removes UV_PAD as it is not working correctly for removing artifacts. Instead, we're going to set a default `spriteAtlasPadding`
> fix: remove uv pad

- CHANGELOG.md
- examples/ai.js
- src/core/contextType.ts
- src/core/taf.ts
- src/math/color.ts
> feat: add jsdoc to all color overloads and allow hexadecimal literal numbers in `color()`

- CHANGELOG.md
- src/core/errors.ts
I've basically removed it from app.run now it just runs at `handleError()` call
> feat: faster error screen ig
